#ifndef TRAIN_CONFIG_H
#define TRAIN_CONFIG_H
#include <stdint.h>
/* Virtual door inputs MUST NEVER authorize a physical motor output. */
#ifndef TRAIN_MOTOR_ENABLED
#define TRAIN_MOTOR_ENABLED 0
#endif
#if TRAIN_MOTOR_ENABLED != 0
#error "Toggle test only: motor output must remain disabled."
#endif
#define TRAIN_MOTOR_RUN_PWM_INITIAL 200U
#define TRAIN_MOTOR_APPROACH_PWM_INITIAL 100U
#define TRAIN_HALL_BASELINE 508U
#define TRAIN_HALL_TOLERANCE 5U
/* 443 -> delta 65: include 65 +/-5 and the earlier 77 +/-5 readings. */
#define TRAIN_HALL_STOP_DELTA_MIN 60U
#define TRAIN_HALL_STOP_DELTA_MAX 82U
#define TRAIN_HALL_SAMPLE_PERIOD_MS 5UL
#define TRAIN_HALL_STABLE_TIME_MS 30UL
#define TRAIN_HALL_CLEAR_DELTA 8U
#define TRAIN_MARKER_REARM_TIME_MS 150UL
#define TRAIN_HALL_RAIL_TIME_MS 250UL
#define TRAIN_KW11_DEBOUNCE_MS 40UL
/* Hand-operated test timeouts, NOT final track timings. */
#define TRAIN_RUNNING_TIMEOUT_MS 120000UL
#define TRAIN_APPROACH_TIMEOUT_MS 120000UL
#define TRAIN_COASTING_WAIT_MS 300UL
#define TRAIN_PSD_OPEN_TIMEOUT_MS 65000UL
#define TRAIN_DOOR_OPEN_TIME_MS 1000UL
#define TRAIN_DOOR_OPEN_TIMEOUT_MS 60000UL
#define TRAIN_DWELL_TIME_MS 5000UL
#define TRAIN_COUNTDOWN_START_SECONDS 5U
#define TRAIN_COUNTDOWN_ZERO_HOLD_MS 300UL
#define TRAIN_DOOR_CLOSE_TIMEOUT_MS 60000UL
#define TRAIN_PSD_CLOSE_TIMEOUT_MS 65000UL
#endif
